site_name: NAME TBD
site_url: https://sabesanhariR.github.io

theme:
  name: material
  palette:
    - scheme: default        # light mode
      primary: indigo        # navbar & header color
      accent: indigo         # hover & link highlight color
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate          # dark mode
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter              # body font (Google Fonts, free)
    code: Roboto Mono        # code block font
  features:
    - navigation.tabs          # top-level sections as tabs
    - navigation.indexes       # section folder pages work
    - navigation.top           # "back to top" button
    - search.suggest           # search autocomplete
    - search.highlight         # highlights search terms on page
    - content.code.copy        # copy button on code blocks
    - toc.follow               # TOC follows your scroll

nav:
  - Home: index.md
  - About: about.md
  - Career:
    - career/landing_page.md
  - Networking:
    - networking/landing_page.md
  - Life:
    - life/landing_page.md

extra:
  generator: false

  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sabesanhari
      name: LinkedIn
    - icon: fontawesome/solid/envelope
      link: mailto:sabesanhari.r@gmail.com
      name: Gmail
    - icon: fontawesome/brands/github
      link: https://github.com/sabesanhariR
      name: GitHub